steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'helloPubSub','source=https://github.com/greenCillah/devCloudFunction','--runtime', 'nodejs8','--trigger-topic=FireFirstFunction']
 